### PR TITLE
[WIP] Docker fixes/Automate docker image deployment

### PR DESCRIPTION
**Pull request by luigi311**
This will fix some formatting on your dockerfiles and it will also simplify your ubuntu all in one dockerfile and automate your deployment to dockerhub for tdarr_aio. I am unsure which dockerfile you are using for the normal build but you can just copy the sections and change the dockerfile or you can tell me which one it is and i can add it.

### CODE REVIEW

**Comment by luigi311** [comment]
Getting an error 
> ulimit: error setting limit (Operation not permitted)

**Comment by luigi311** [comment]
Using your version of mongodb fixes the ulimit problem. I am running into the following issue 
``` 
Cannot find module 'fibers'
```
Unfortunately i am not experienced with npm

**Comment by luigi311** [comment]
Looks like fibers is a error with some versioning. I updated the .meteor packages to 1.8.3 and now i am getting
```
 Error: Cannot find module 'reify/lib/runtime'
```

**Comment by HaveAGitGat** [comment]
> I am unsure which dockerfile you are using for the normal build but you can just copy the sections and change the dockerfile or you can tell me which one it is and i can add it.

tdarr_aio - https://github.com/HaveAGitGat/Tdarr/blob/master/Dockerfile.ubuntu
tdarr - https://github.com/HaveAGitGat/Tdarr/blob/master/Dockerfile.alpine

**Comment by luigi311** [comment]
I will give that a try

**Comment by luigi311** [comment]
Still throws the same error.
```
 Error: Cannot find module 'reify/lib/runtime'
```
Can you check the docker github actions file and see if you are doing anything different when you are building the meteor files?

**Comment by HaveAGitGat** [comment]
Does this work?

`meteor build --server localhost:8265 --directory Tdarr-Bundle  --architecture os.linux.x86_64`

**Comment by luigi311** [comment]
Still a no go. It is still returning the same error. Let me try going back to the original .meteor files and trying to build with 1.8.1 since that's what you are using correct?

**Comment by luigi311** [comment]
That was a no go, 1.8.1 with the original .meteor files generates a fibers error on my local test.

**Comment by luigi311** [comment]
Just to make sure i was not going crazy, i grabbed your bundle out of the aio container and put it in the folder and did a local build and it worked, So it has to be something with meteor that is different on your machine than it is on mine and the meteor container.

**Comment by luigi311** [comment]
Are your files in .meteor different to those that are in your master branch?

**Comment by HaveAGitGat** [comment]
That’s interesting. You could maybe try building using the dev branch but it should be mostly the same.

**Comment by HaveAGitGat** [comment]
No the files in my .meteor are the same as master.

**Comment by luigi311** [comment]
Looking at the dev branch it looks like they are the same files. Hmmm im running out of ideas. I was under the impression that meteor configurations are all compartmentalized to the project itself, so inside the .meteor folder it contains everything it needs to install and configure meteor exactly the same way on every machine. If thats true then your meteor configuration would be the same as mine, in theory. Are you able to build a bundle folder and run the aio docker container with that new bundle?

**Comment by HaveAGitGat** [comment]
hello, I just built and ran tdarr_aio for the latest release (1.103) and all is working fine.

**Comment by HaveAGitGat** [comment]
I'll update the docker files and associated files for you to have another go

**Comment by HaveAGitGat** [comment]
Have a look at:
https://github.com/HaveAGitGat/Tdarr/tree/master/Docker_files/Ubuntu

**Comment by luigi311** [comment]
Ill give it another look over and see if i can get it to work.

**Comment by luigi311** [comment]
Im going to start fresh. Will start again once i think i got this thing working or need help

**Comment by HaveAGitGat** [comment]
Ok. Someone gave some Gitlab tips here:
https://forums.meteor.com/t/auto-build-win-linux-macos-meteor-app-push-to-docker/51464/4

Would like to keep everything on Github though. I’ll try and have a read through the documentation next week.

**Comment by luigi311** [comment]
Wow even less progress now lol. I am getting a 
```
mongodb: unrecognized service
```

**Comment by luigi311** [comment]
The alpine fails to even install handbrake due to unsatisfiable constraints with so:libdvdread.so.7 (missing) and installing libdvdread does not solve it.
